# This is a template file. Actual secrets should be managed securely via AWS Secrets Manager, 
# Kubernetes external secrets operator, or directly applied with proper encryption.

apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: mindlyf
type: Opaque
data:
  # These are placeholders and should be replaced with actual values
  AWS_COGNITO_USER_POOL_ID: ${BASE64_ENCODED_USER_POOL_ID}
  AWS_COGNITO_CLIENT_ID: ${BASE64_ENCODED_CLIENT_ID}
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: mindlyf
type: Opaque
data:
  # These are placeholders and should be replaced with actual values
  OPENAI_API_KEY: ${BASE64_ENCODED_OPENAI_API_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: mindlyf
type: Opaque
data:
  # These are placeholders and should be replaced with actual values
  DB_USERNAME: ${BASE64_ENCODED_DB_USERNAME}
  DB_PASSWORD: ${BASE64_ENCODED_DB_PASSWORD}
  DB_HOST: ${BASE64_ENCODED_DB_HOST}
  DB_PORT: ${BASE64_ENCODED_DB_PORT}
  DB_NAME: ${BASE64_ENCODED_DB_NAME}
---
apiVersion: v1
kind: Secret
metadata:
  name: teletherapy-secrets
  namespace: mindlyf
type: Opaque
data:
  # These are placeholders and should be replaced with actual values
  TURN_SECRET: ${BASE64_ENCODED_TURN_SECRET}
  SSL_KEY: ${BASE64_ENCODED_SSL_KEY}
  SSL_CERT: ${BASE64_ENCODED_SSL_CERT} 