version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - auth-service
      - ai-service
    networks:
      - mindlyf-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - AWS_REGION=us-east-1
      - COGNITO_USER_POOL_ID=your-user-pool-id
      - COGNITO_CLIENT_ID=your-client-id
      - JWT_SECRET=your-jwt-secret
    networks:
      - mindlyf-network

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/app
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=your-openai-api-key
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mindlyf_ai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - mindlyf-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mindlyf
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mindlyf-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mindlyf-network

networks:
  mindlyf-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 